name: CreatePDFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
      with:
        markdown_dir: /
    - uses: actions/upload-artifact@v2
      with:
        name: platform-architecture-docs
        path: tmp
